# Generated by Django 4.0.4 on 2022-06-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propuestaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(max_length=50)),
                ('description_skill', models.CharField(max_length=320)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuestaApp.aspirante')),
            ],
        ),
    ]
